import type { PcrmPage } from "./pcrm-content";

const BASE = "https://www.pcrm.org";

type ManualPageSpec = readonly [
  path: string,
  titleEn: string,
  titleVi: string,
  summaryEn: string,
  summaryVi: string,
];

function createPage([path, titleEn, titleVi, summaryEn, summaryVi]: ManualPageSpec): PcrmPage & { path: string } {
  return {
    url: `${BASE}${path}`,
    path,
    title: titleEn,
    title_en: titleEn,
    title_vi: titleVi,
    description: summaryEn,
    description_en: summaryEn,
    description_vi: summaryVi,
    h1: [titleEn]
      ,
    h1_en: [titleEn],
    h1_vi: [titleVi],
    h2: [],
    h2_en: [],
    h2_vi: [],
    h3: [],
    h3_en: [],
    h3_vi: [],
    paragraphs: [summaryEn],
    paragraphs_en: [summaryEn],
    paragraphs_vi: [summaryVi],
    images: [],
    links: [],
  };
}

const manualPageSpecs: ManualPageSpec[] = [
  [
    "/good-nutrition/plant-based-diets",
    "Plant-Based Diets",
    "Chế độ ăn thực vật",
    "Foundational guides and resources about plant-based eating.",
    "Tài liệu nền tảng và tài nguyên về chế độ ăn thực vật.",
  ],
  [
    "/good-nutrition/plant-based-diets/nutrition-faq",
    "Nutrition FAQ",
    "Câu hỏi thường gặp về dinh dưỡng",
    "Answers to common questions about plant-based nutrition.",
    "Giải đáp các câu hỏi thường gặp về dinh dưỡng thực vật.",
  ],
  [
    "/good-nutrition/nutrition-for-clinicians",
    "Nutrition for Clinicians",
    "Dinh dưỡng cho bác sĩ",
    "Practical nutrition resources for healthcare professionals.",
    "Tài liệu dinh dưỡng thực hành dành cho nhân viên y tế.",
  ],
  [
    "/good-nutrition/nutrition-for-clinicians/medical-students",
    "Nutrition for Medical Students",
    "Dinh dưỡng cho sinh viên y khoa",
    "Introductory resources for medical students learning plant-based nutrition.",
    "Tài liệu nhập môn cho sinh viên y khoa tìm hiểu dinh dưỡng thực vật.",
  ],
  [
    "/good-nutrition/nutrition-information/the-carbohydrate-advantage",
    "The Carbohydrate Advantage",
    "Lợi thế của carbohydrate",
    "Why smart carbohydrate choices matter in a plant-based diet.",
    "Vì sao lựa chọn carbohydrate phù hợp rất quan trọng trong chế độ ăn thực vật.",
  ],
  [
    "/good-nutrition/nutrition-information/soy-and-health",
    "Soy and Health",
    "Đậu nành và sức khỏe",
    "Evidence-based guidance on soy foods and health outcomes.",
    "Hướng dẫn dựa trên bằng chứng về đậu nành và sức khỏe.",
  ],
  [
    "/good-nutrition/nutrition-information/lowering-cholesterol-with-a-plant-based-diet",
    "Lowering Cholesterol with a Plant-Based Diet",
    "Giảm cholesterol bằng chế độ ăn thực vật",
    "Ways to support healthy cholesterol levels through food choices.",
    "Cách hỗ trợ mức cholesterol lành mạnh thông qua lựa chọn thực phẩm.",
  ],
  [
    "/good-nutrition/nutrition-information/chicken",
    "Chicken",
    "Thịt gà",
    "Nutrition guidance and concerns related to chicken consumption.",
    "Hướng dẫn dinh dưỡng và các lưu ý liên quan đến việc ăn thịt gà.",
  ],
  [
    "/good-nutrition/nutrition-information/processed-meat",
    "Processed Meat",
    "Thịt chế biến sẵn",
    "Health concerns and evidence about processed meat.",
    "Các lo ngại sức khỏe và bằng chứng về thịt chế biến sẵn.",
  ],
  [
    "/good-nutrition/healthy-communities",
    "Healthy Communities",
    "Cộng đồng khỏe mạnh",
    "Community-based programs and outreach resources.",
    "Chương trình cộng đồng và tài nguyên truyền thông.",
  ],
  [
    "/good-nutrition/nutrition-programs-policies",
    "Nutrition Programs & Policies",
    "Chương trình và chính sách dinh dưỡng",
    "Program and policy resources supporting healthier food environments.",
    "Tài nguyên về chương trình và chính sách hỗ trợ môi trường ăn uống lành mạnh.",
  ],
  [
    "/ethical-science/ethical-education-and-training/paramedic-training",
    "Paramedic Training",
    "Đào tạo nhân viên cấp cứu",
    "Training resources focused on humane and effective medical education.",
    "Tài liệu đào tạo hướng tới giáo dục y khoa hiệu quả và nhân đạo.",
  ],
  [
    "/ethical-science/animals-in-medical-research",
    "Animals in Medical Research",
    "Động vật trong nghiên cứu y khoa",
    "Alternatives, analysis, and discussion of animal use in research.",
    "Các giải pháp thay thế, phân tích và thảo luận về việc dùng động vật trong nghiên cứu.",
  ],
  [
    "/ethical-science/animals-in-medical-research/alzheimers-disease-research-without-animals",
    "Alzheimer's Disease Research Without Animals",
    "Nghiên cứu Alzheimer không dùng động vật",
    "Human-relevant research and alternatives for Alzheimer’s studies.",
    "Nghiên cứu phù hợp với con người và các giải pháp thay thế cho nghiên cứu Alzheimer.",
  ],
  [
    "/ethical-science/ethical-education-and-training/ERA21",
    "ERA21",
    "ERA21",
    "Alternative surgical training resources and education initiatives.",
    "Tài nguyên đào tạo phẫu thuật thay thế và các sáng kiến giáo dục.",
  ],
  [
    "/ethical-science/animal-testing-and-alternatives",
    "Animal Testing and Alternatives",
    "Thử nghiệm trên động vật và giải pháp thay thế",
    "Overview of modern research methods and alternatives to animal testing.",
    "Tổng quan về các phương pháp nghiên cứu hiện đại và giải pháp thay thế thử nghiệm động vật.",
  ],
  [
    "/ethical-science/animal-testing-and-alternatives/animal-free-antibodies",
    "Animal-Free Antibodies",
    "Kháng thể không dùng động vật",
    "Methods and resources for producing antibodies without animals.",
    "Phương pháp và tài nguyên sản xuất kháng thể mà không cần động vật.",
  ],
  [
    "/ethical-science/animal-testing-and-alternatives/cruelty-free-cosmetics",
    "Cruelty-Free Cosmetics",
    "Mỹ phẩm không thử nghiệm trên động vật",
    "How cosmetic testing can move away from animal use.",
    "Cách ngành mỹ phẩm có thể chuyển sang không dùng động vật.",
  ],
  [
    "/ethical-science/animal-testing-and-alternatives/human-tissue-research",
    "Human Tissue Research",
    "Nghiên cứu mô người",
    "Human tissue-based approaches to biomedical research.",
    "Các phương pháp nghiên cứu y sinh dựa trên mô người.",
  ],
  [
    "/clinical-research/endometriosis",
    "Endometriosis",
    "Lạc nội mạc tử cung",
    "Clinical research and nutrition-related resources on endometriosis.",
    "Nghiên cứu lâm sàng và tài nguyên dinh dưỡng liên quan đến lạc nội mạc tử cung.",
  ],
  [
    "/clinical-research/fighting-hot-flashes-with-diet",
    "Fighting Hot Flashes with Diet",
    "Kiểm soát bốc hỏa bằng chế độ ăn",
    "Diet strategies and clinical guidance for managing hot flashes.",
    "Chiến lược dinh dưỡng và hướng dẫn lâm sàng để kiểm soát bốc hỏa.",
  ],
  [
    "/health-topics/alzheimers",
    "Alzheimer's",
    "Alzheimer",
    "Research-backed guidance and articles related to Alzheimer’s disease.",
    "Tài liệu và bài viết dựa trên bằng chứng về bệnh Alzheimer.",
  ],
  [
    "/health-topics/arthritis",
    "Arthritis",
    "Viêm khớp",
    "Research-backed guidance and articles related to arthritis.",
    "Tài liệu và bài viết dựa trên bằng chứng về viêm khớp.",
  ],
  [
    "/health-topics/asthma",
    "Asthma",
    "Hen suyễn",
    "Research-backed guidance and articles related to asthma.",
    "Tài liệu và bài viết dựa trên bằng chứng về hen suyễn.",
  ],
  [
    "/health-topics/breast-cancer",
    "Breast Cancer",
    "Ung thư vú",
    "Research-backed guidance and articles related to breast cancer.",
    "Tài liệu và bài viết dựa trên bằng chứng về ung thư vú.",
  ],
  [
    "/health-topics/coronavirus",
    "Coronavirus",
    "Coronavirus",
    "Research-backed guidance and articles related to coronavirus.",
    "Tài liệu và bài viết dựa trên bằng chứng về coronavirus.",
  ],
  [
    "/health-topics/healthy-bones",
    "Healthy Bones",
    "Xương khỏe mạnh",
    "Research-backed guidance and articles related to bone health.",
    "Tài liệu và bài viết dựa trên bằng chứng về sức khỏe xương.",
  ],
  [
    "/health-topics/heart-disease",
    "Heart Disease",
    "Bệnh tim",
    "Research-backed guidance and articles related to heart disease.",
    "Tài liệu và bài viết dựa trên bằng chứng về bệnh tim.",
  ],
  [
    "/health-topics/migraines",
    "Migraines",
    "Đau nửa đầu",
    "Research-backed guidance and articles related to migraines.",
    "Tài liệu và bài viết dựa trên bằng chứng về đau nửa đầu.",
  ],
  [
    "/health-topics/ovarian-cancer",
    "Ovarian Cancer",
    "Ung thư buồng trứng",
    "Research-backed guidance and articles related to ovarian cancer.",
    "Tài liệu và bài viết dựa trên bằng chứng về ung thư buồng trứng.",
  ],
  [
    "/health-topics/polycystic-ovarian-syndrome",
    "Polycystic Ovarian Syndrome",
    "Hội chứng buồng trứng đa nang",
    "Research-backed guidance and articles related to PCOS.",
    "Tài liệu và bài viết dựa trên bằng chứng về hội chứng buồng trứng đa nang.",
  ],
  [
    "/about-us/careers",
    "Careers",
    "Tuyển dụng",
    "Open roles and opportunities with PCRM.",
    "Các vị trí tuyển dụng và cơ hội nghề nghiệp tại PCRM.",
  ],
  [
    "/about-us/careers/internships",
    "Internships",
    "Thực tập",
    "Student and early-career internship opportunities.",
    "Cơ hội thực tập cho sinh viên và người mới bắt đầu sự nghiệp.",
  ],
  [
    "/about-us/financial-report",
    "Annual & Financial Reports",
    "Báo cáo thường niên và tài chính",
    "Annual reports and financial information.",
    "Báo cáo thường niên và thông tin tài chính.",
  ],
  [
    "/events",
    "Events",
    "Sự kiện",
    "Upcoming events, programs, and featured activities.",
    "Các sự kiện, chương trình và hoạt động nổi bật sắp tới.",
  ],
  [
    "/news",
    "News",
    "Tin tức",
    "Latest news, science updates, and event coverage from PCRM.",
    "Tin tức mới nhất, cập nhật khoa học và tường thuật sự kiện từ PCRM.",
  ],
  [
    "/news/health-nutrition",
    "Health & Nutrition News",
    "Tin tức sức khỏe và dinh dưỡng",
    "Research-backed nutrition news and articles.",
    "Tin tức và bài viết dinh dưỡng dựa trên bằng chứng.",
  ],
  [
    "/news/innovative-science-news",
    "Innovative Science News",
    "Tin khoa học đổi mới",
    "News about humane, human-relevant science.",
    "Tin tức về khoa học nhân văn và phù hợp với con người.",
  ],
  [
    "/news/media-center",
    "Media Center",
    "Trung tâm truyền thông",
    "Press materials and media resources.",
    "Tài liệu báo chí và nguồn lực dành cho truyền thông.",
  ],
  [
    "/ways-to-give",
    "Ways to Give",
    "Các cách ủng hộ",
    "Donation methods and support options.",
    "Các phương thức quyên góp và lựa chọn ủng hộ.",
  ],
];

export const manualPages = manualPageSpecs.map(createPage);